### ISSUE TITLE
Java 対応

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#119]
親 issue: #116 

雑に提出数を数えたところユーザ数第 3 位らしいことが分かった。Rust や C# の 3 倍ぐらい

**Comment by Maruoka842** [comment]
Javaでhoge.test.javaというファイルを動かすにはhoge.testという名前のクラスを作る必要があるのですが、「.」は名前に使えません。hoge_test.javaで動くようにするなど特別な処置が必要だと思います。

**Comment by kmyk** [comment]
@Maruoka842 その問題の対策のための機能を足しました。以下のように設定してください

``` toml
[language.java]
verification_file_suffix = "_test.java"
compile = "..."
...
```

(いま足したばかりの機能でまだ誰もまともに使ってないので、なにかバグがあるかもしれません。そのときはまた報告してください)
