### ISSUE TITLE
`Install cargo-udeps for Rust` fails

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/verification-helper#395]
## Summary / 概要

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">oj-verify が変な failure 起こしてる<a href="https://t.co/mwc02ZMWdG">https://t.co/mwc02ZMWdG</a></p>&mdash; KoD (@d7511168) <a href="https://twitter.com/d7511168/status/1439442242754646019?ref_src=twsrc%5Etfw">September 19, 2021</a></blockquote>

## Steps to reproduce / 再現方法

``` yaml
    # required only if you set `languages.rust.list_dependencies_backend.kind` to `"cargo-udeps"`
    - name: Install cargo-udeps for Rust
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
        use-tool-cache: true
```

## Actual behavior / 実際の挙動

https://github.com/KodamaD/proconlib/runs/3643175354

``` console
Run actions-rs/install@v0.1
Tool cache is explicitly enabled via the Action input
Downloading from the tool cache
Falling back to the `cargo install` command
Installing "cargo-udeps = latest"
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

## Other notes / その他

-  cc @KodamaD
