### ISSUE TITLE
`actions/checkout@v3` だと gh-pages の更新に失敗する

### ISSUE THREAD

**Issue by kzrnm** [online-judge-tools/verification-helper#406]
## Steps to reproduce / 再現方法

1. GitHub Actions の checkout を `uses: actions/checkout@v3` で行う

environments:

-   version: (please write the versions of related things, e.g. `$ oj --version`)

## Expected behavior / 期待される挙動

gh-pages が更新される

## Actual behavior / 実際の挙動

``` console
error: pathspec 'gh-pages' did not match any file(s) known to git
```

というエラーで checkout に失敗してしまう。

## Other notes / その他

-   Will you try to create a pull request?
    -   yes / no

**Comment by kzrnm** [comment]
`fetch-depth: 0` にすれば大丈夫です

```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```
